import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/**
 * Regenerates `src/abi/perago-contracts.ts` from the compiled Foundry artifacts,
 * so the TypeScript ABI surface can never drift from the Solidity it claims to
 * describe. Run `forge build` in `packages/contracts` first, then:
 *
 *   pnpm --filter @perago/sdk sync:abi
 *
 * The generated file is committed; a nonempty `git diff` after this script means
 * the Solidity interface changed without the SDK surface being updated.
 */
const EXPORTS = [
  {
    artifact: "IPeragoAdapter.sol/IPeragoAdapter.json",
    exportName: "peragoAdapterAbi",
    summary: "Action adapter every Perago execution path routes through.",
  },
  {
    artifact: "IPeragoVerifier.sol/IPeragoVerifier.json",
    exportName: "peragoVerifierAbi",
    summary:
      "Deterministic verifier that measures and proves an adapter result.",
  },
  {
    artifact: "PeragoAcpHook.sol/PeragoAcpHook.json",
    exportName: "peragoAcpHookAbi",
    summary: "Inert ERC-8183 hook the deployed APEX kernel requires per job.",
  },
  {
    artifact: "MandateExecutor.sol/MandateExecutor.json",
    exportName: "mandateExecutorAbi",
    summary:
      "Authority boundary: account registration, mandate authorization, and terminal state.",
  },
  {
    artifact: "PancakeV3SwapAdapter.sol/PancakeV3SwapAdapter.json",
    exportName: "pancakeV3SwapAdapterAbi",
    summary:
      "Pinned-pool exact-input swap adapter; its errors are mapped reason codes.",
  },
  {
    artifact: "SwapVerifier.sol/SwapVerifier.json",
    exportName: "swapVerifierAbi",
    summary: "Measures swap output at the signed recipient.",
  },
  {
    artifact: "CakeStakeAdapter.sol/CakeStakeAdapter.json",
    exportName: "cakeStakeAdapterAbi",
    summary:
      "Pinned CAKE Pool flexible-stake adapter; positionOf names each recipient's holder.",
  },
  {
    artifact: "CakeStakePosition.sol/CakeStakePosition.json",
    exportName: "cakeStakePositionAbi",
    summary: "A recipient's own CAKE Pool account; only its owner withdraws.",
  },
  {
    artifact: "StakeVerifier.sol/StakeVerifier.json",
    exportName: "stakeVerifierAbi",
    summary: "Measures pool shares of the signed recipient's holder.",
  },
  {
    artifact: "MandateSimulationHarness.sol/MandateSimulationHarness.json",
    exportName: "mandateSimulationHarnessAbi",
    runtimeExportName: "mandateSimulationHarnessRuntime",
    summary:
      "Never deployed: installed at the account by an eth_call state override to run the exact UserOperation calls.",
  },
];

const artifactUrl = (artifact) =>
  new URL(`../../contracts/out/${artifact}`, import.meta.url);

const blocks = EXPORTS.map(
  ({ artifact, exportName, runtimeExportName, summary }) => {
    const path = fileURLToPath(artifactUrl(artifact));
    const { abi, deployedBytecode } = JSON.parse(readFileSync(path, "utf8"));
    if (!Array.isArray(abi) || abi.length === 0) {
      throw new Error(`${artifact} has no ABI; run forge build first`);
    }
    const abiBlock = `/** ${summary} */\nexport const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
    if (!runtimeExportName) return abiBlock;
    const runtime = deployedBytecode?.object;
    if (typeof runtime !== "string" || !/^0x[0-9a-f]+$/u.test(runtime)) {
      throw new Error(
        `${artifact} has no runtime bytecode; run forge build first`,
      );
    }
    return `${abiBlock}\n/** Runtime code of the contract above, for state overrides only. */\nexport const ${runtimeExportName} = "${runtime}" as const;\n`;
  },
);

const header = `// Generated by \`pnpm --filter @perago/sdk sync:abi\` from the Foundry artifacts
// in packages/contracts/out. Do not edit by hand: edit the Solidity interface and
// regenerate, so this surface always matches compiled bytecode.
`;

const target = fileURLToPath(
  new URL("../src/abi/perago-contracts.ts", import.meta.url),
);
writeFileSync(target, `${header}\n${blocks.join("\n")}`);
console.log(`wrote ${EXPORTS.length} ABIs to ${target}`);
