// Generated by `pnpm --filter @perago/sdk sync:abi` from the Foundry artifacts
// in packages/contracts/out. Do not edit by hand: edit the Solidity interface and
// regenerate, so this surface always matches compiled bytecode.

/** Action adapter every Perago execution path routes through. */
export const peragoAdapterAbi = [
  {
    type: "function",
    name: "execute",
    inputs: [
      {
        name: "mandate",
        type: "tuple",
        internalType: "struct PeragoTypes.TaskMandate",
        components: [
          {
            name: "account",
            type: "address",
            internalType: "address",
          },
          {
            name: "rootOwner",
            type: "address",
            internalType: "address",
          },
          {
            name: "ownerEpoch",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "executor",
            type: "address",
            internalType: "address",
          },
          {
            name: "chainId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "nonce",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "expiresAt",
            type: "uint48",
            internalType: "uint48",
          },
          {
            name: "policyHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "intentHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "planHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "simulationHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "adapter",
            type: "address",
            internalType: "address",
          },
          {
            name: "adapterSelector",
            type: "bytes4",
            internalType: "bytes4",
          },
          {
            name: "inputToken",
            type: "address",
            internalType: "address",
          },
          {
            name: "maxInput",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "outputToken",
            type: "address",
            internalType: "address",
          },
          {
            name: "minOutput",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "recipient",
            type: "address",
            internalType: "address",
          },
          {
            name: "actionHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "postconditionHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "commerceContract",
            type: "address",
            internalType: "address",
          },
          {
            name: "commerceJobId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
      {
        name: "action",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "result",
        type: "tuple",
        internalType: "struct PeragoTypes.AdapterResult",
        components: [
          {
            name: "inputSpent",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "outputOrPositionReceived",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "protocolEvidenceHash",
            type: "bytes32",
            internalType: "bytes32",
          },
        ],
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "kind",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "validate",
    inputs: [
      {
        name: "mandate",
        type: "tuple",
        internalType: "struct PeragoTypes.TaskMandate",
        components: [
          {
            name: "account",
            type: "address",
            internalType: "address",
          },
          {
            name: "rootOwner",
            type: "address",
            internalType: "address",
          },
          {
            name: "ownerEpoch",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "executor",
            type: "address",
            internalType: "address",
          },
          {
            name: "chainId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "nonce",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "expiresAt",
            type: "uint48",
            internalType: "uint48",
          },
          {
            name: "policyHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "intentHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "planHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "simulationHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "adapter",
            type: "address",
            internalType: "address",
          },
          {
            name: "adapterSelector",
            type: "bytes4",
            internalType: "bytes4",
          },
          {
            name: "inputToken",
            type: "address",
            internalType: "address",
          },
          {
            name: "maxInput",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "outputToken",
            type: "address",
            internalType: "address",
          },
          {
            name: "minOutput",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "recipient",
            type: "address",
            internalType: "address",
          },
          {
            name: "actionHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "postconditionHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "commerceContract",
            type: "address",
            internalType: "address",
          },
          {
            name: "commerceJobId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
      {
        name: "action",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "normalizedActionHash",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "verifier",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
] as const;

/** Deterministic verifier that measures and proves an adapter result. */
export const peragoVerifierAbi = [
  {
    type: "function",
    name: "measure",
    inputs: [
      {
        name: "mandate",
        type: "tuple",
        internalType: "struct PeragoTypes.TaskMandate",
        components: [
          {
            name: "account",
            type: "address",
            internalType: "address",
          },
          {
            name: "rootOwner",
            type: "address",
            internalType: "address",
          },
          {
            name: "ownerEpoch",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "executor",
            type: "address",
            internalType: "address",
          },
          {
            name: "chainId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "nonce",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "expiresAt",
            type: "uint48",
            internalType: "uint48",
          },
          {
            name: "policyHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "intentHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "planHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "simulationHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "adapter",
            type: "address",
            internalType: "address",
          },
          {
            name: "adapterSelector",
            type: "bytes4",
            internalType: "bytes4",
          },
          {
            name: "inputToken",
            type: "address",
            internalType: "address",
          },
          {
            name: "maxInput",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "outputToken",
            type: "address",
            internalType: "address",
          },
          {
            name: "minOutput",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "recipient",
            type: "address",
            internalType: "address",
          },
          {
            name: "actionHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "postconditionHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "commerceContract",
            type: "address",
            internalType: "address",
          },
          {
            name: "commerceJobId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
      {
        name: "action",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "value",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "contextHash",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "verifierId",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "verify",
    inputs: [
      {
        name: "mandate",
        type: "tuple",
        internalType: "struct PeragoTypes.TaskMandate",
        components: [
          {
            name: "account",
            type: "address",
            internalType: "address",
          },
          {
            name: "rootOwner",
            type: "address",
            internalType: "address",
          },
          {
            name: "ownerEpoch",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "executor",
            type: "address",
            internalType: "address",
          },
          {
            name: "chainId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "nonce",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "expiresAt",
            type: "uint48",
            internalType: "uint48",
          },
          {
            name: "policyHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "intentHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "planHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "simulationHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "adapter",
            type: "address",
            internalType: "address",
          },
          {
            name: "adapterSelector",
            type: "bytes4",
            internalType: "bytes4",
          },
          {
            name: "inputToken",
            type: "address",
            internalType: "address",
          },
          {
            name: "maxInput",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "outputToken",
            type: "address",
            internalType: "address",
          },
          {
            name: "minOutput",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "recipient",
            type: "address",
            internalType: "address",
          },
          {
            name: "actionHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "postconditionHash",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "commerceContract",
            type: "address",
            internalType: "address",
          },
          {
            name: "commerceJobId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
      {
        name: "action",
        type: "bytes",
        internalType: "bytes",
      },
      {
        name: "beforeValue",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "beforeContext",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "result",
        type: "tuple",
        internalType: "struct PeragoTypes.AdapterResult",
        components: [
          {
            name: "inputSpent",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "outputOrPositionReceived",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "protocolEvidenceHash",
            type: "bytes32",
            internalType: "bytes32",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "evidence",
        type: "tuple",
        internalType: "struct PeragoTypes.VerificationEvidence",
        components: [
          {
            name: "inputSpent",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "observedOutputOrPositionDelta",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "evidenceHash",
            type: "bytes32",
            internalType: "bytes32",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
] as const;

/** Inert ERC-8183 hook the deployed APEX kernel requires per job. */
export const peragoAcpHookAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "commerce_",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "afterAction",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "",
        type: "bytes4",
        internalType: "bytes4",
      },
      {
        name: "",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "beforeAction",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "",
        type: "bytes4",
        internalType: "bytes4",
      },
      {
        name: "",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "commerce",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "supportsInterface",
    inputs: [
      {
        name: "interfaceId",
        type: "bytes4",
        internalType: "bytes4",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "error",
    name: "UnauthorizedCaller",
    inputs: [
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
    ],
  },
] as const;
